### ISSUE TITLE
Gzip IO异常有问题

### ISSUE THREAD

**Issue by JyuuAra** [xuan525/BiliLiveDanmaku#1]
代码运行到
`gZipStream.CopyTo(decompressedStream);`
抛出IO异常, 感觉和这个有点像？
[https://stackoverflow.com/questions/20850703/cant-inflate-with-c-sharp-using-deflatestream](url)

```
IOException: Corrupted data ReadInternal
System.IO.Compression.DeflateStreamNative.CheckResult (System.Int32 result, System.String where) (at <aa976c2104104b7ca9e1785715722c9d>:0)
System.IO.Compression.DeflateStreamNative.ReadZStream (System.IntPtr buffer, System.Int32 length) (at <aa976c2104104b7ca9e1785715722c9d>:0)
System.IO.Compression.DeflateStream.ReadInternal (System.Byte[] array, System.Int32 offset, System.Int32 count) (at <aa976c2104104b7ca9e1785715722c9d>:0)
System.IO.Compression.DeflateStream.Read (System.Byte[] array, System.Int32 offset, System.Int32 count) (at <aa976c2104104b7ca9e1785715722c9d>:0)
System.IO.Compression.GZipStream.Read (System.Byte[] array, System.Int32 offset, System.Int32 count) (at <aa976c2104104b7ca9e1785715722c9d>:0)
System.IO.Stream.InternalCopyTo (System.IO.Stream destination, System.Int32 bufferSize) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.IO.Stream.CopyTo (System.IO.Stream destination) (at <695d1cc93cca45069c528c15c9fdd749>:0)
(wrapper remoting-invoke-with-check) System.IO.Stream.CopyTo(System.IO.Stream)
BiliLive.BiliPackReader.ReadPacksAsync () (at Assets/BiliConnect/Bili/BiliPackReader.cs:180)
```

**Comment by xuan25** [comment]
请问此异常是在什么情况下抛出的？是确定性必然出现，还是大概率随机出现，再或者小概率随机出现？我自己运行是正常的，没能复现出您的异常，因此请提供您的程序版本以及环境信息。

我的运行信息：
程序版本：commit 5ce0f24
.NET Framework 版本：4.7.2
Window 版本：20H2 (OS Build 19042.1052)

**Comment by JyuuAra** [comment]
> 请问此异常是在什么情况下抛出的？是确定性必然出现，还是大概率随机出现，再或者小概率随机出现？我自己运行是正常的，没能复现出您的异常，因此请提供您的程序版本以及环境信息。
> 
> 我的运行信息：
> 程序版本：commit [5ce0f24](https://github.com/xuan525/BiliLiveDanmaku/commit/5ce0f248df2916c825f3c70492911feba157ddbd)
> .NET Framework 版本：4.7.2
> Window 版本：20H2 (OS Build 19042.1052)

对不起回复晚了 

1: 请问此异常是在什么情况下抛出的？
是接收到直播间用户弹幕时，代码走到gZipStream.CopyTo位置抛出

2: 是确定性必然出现，还是大概率随机出现，再或者小概率随机出现？
确定性必然出现

3.程序版本以及环境信息。
程序版本是最新的commit
.NetFramework版本 4.7.1
Windows 版本 21H1
还有其他条件是在Unity环境下

**Comment by xuan25** [comment]
# 可能的解决方案

## 概要

经过测试，我认为这可能是.NET Framework 4.7.1的一个问题，升级版本到.NET Framework 4.7.2即可解决。

## 分析

在.NET Framework 4.7.1下，我得到了类似的报错：

```
An unexpected and unrecoverable problem has occourred. 
The software will now crash.

Captured an unhandled exception：
System.IO.InvalidDataException

Exception Message：
The magic number in GZip header is not correct. Make sure you are passing in a GZip stream.

Exception StackTrace：
   at System.IO.Compression.GZipDecoder.ReadHeader(InputBuffer input)
   at System.IO.Compression.Inflater.Decode()
   at System.IO.Compression.Inflater.Inflate(Byte[] bytes, Int32 offset, Int32 length)
   at System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.Compression.GZipStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.Stream.InternalCopyTo(Stream destination, Int32 bufferSize)
   at System.IO.Stream.CopyTo(Stream destination)
   at BiliLive.BiliPackReader.ReadPacksAsync() in C:\Users\shanb\Documents\GitHub\BiliLiveDanmaku\BiliLiveDanmaku\BiliLiveDanmaku\Bili\BiliPackReader.cs:line 180
   at BiliLive.BiliLiveListener.<StartEventListener>b__83_0() in C:\Users\shanb\Documents\GitHub\BiliLiveDanmaku\BiliLiveDanmaku\BiliLiveDanmaku\Bili\BiliLiveListener.cs:line 346
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

通过检查数据，我发现流头为78 DA，应该是ZLIB的头部。经过分析发现，头部没有问题，其使用的压缩算法基本上就是默认的，同时使用最大压缩。因此猜测可能是该版本的GZipStream不支持ZLIB头部。

## 附

具体对于流头的分析如下：

### Header from stream (CMF and FLG):

| Byte 1   | Byte 2   |
| -------- | -------- |
| 78       | DA       |
| 01111000 | 11011010 |

### Analysis

| Field                               | Binary | Decimal | Description                                               |
| ----------------------------------- | ------ | ------- | --------------------------------------------------------- |
| CM (Compression method)             | 1000   | 8       | "deflate" compression method with a window size up to 32K |
| CINFO (Compression info)            | 0111   | 7       | 32K window size                                           |
| FCHECK (Check bits for CMF and FLG) | 11010  | -       | -                                                         |
| FDICT (Preset dictionary)           | 0      | 0       | Preset dictionary not set                                 |
| FLEVEL (Compression level)          | 11     | 3       | compressor used maximum compression, slowest algorithm    |

## 参考

ZLIB Compressed Data Format Specification version 3.3: https://datatracker.ietf.org/doc/html/rfc1950

**Comment by xuan25** [comment]
# .NET Framework 4.7.1 下的解决方案

另一种解决方案是自定义对ZLIB数据头部的检查，然后直接对其中的Deflate数据进行解码。

此时应修改 Bili/BiliPackReader.cs 中的内容如下 (172 行开始)

```C#
                case DataTypes.Gz:
                    List<IPack> packs = new List<IPack>();

                    // Skip 2 bytes of zlib header (assuming the header is 78 DA)
                    byte[] deflateBuffer = payloadBuffer.Skip(2).ToArray();
                    using (MemoryStream compressedStream = new MemoryStream(deflateBuffer))
                    {
                        using (DeflateStream deflateStream = new DeflateStream(compressedStream, CompressionMode.Decompress))
                        {
                            using (MemoryStream decompressedStream = new MemoryStream())
                            {
                                deflateStream.CopyTo(decompressedStream);
                                decompressedStream.Position = 0;

                                while (decompressedStream.Position != decompressedStream.Length)
                                {
                                    IPack[] innerPackes = new BiliPackReader(decompressedStream).ReadPacksAsync();
                                    packs.AddRange(innerPackes);
                                }

                            }
                        }
                    }
                    return packs.ToArray();
```

注：这是个简化的解决方案，其中假设ZLIB头为78 DA，并直接跳过了头部的检查。在正式项目中最好对ZLIB头部执行额外的检查。

**Comment by JyuuAra** [comment]
> # .NET Framework 4.7.1 下的解决方案
> 另一种解决方案是自定义对ZLIB数据头部的检查，然后直接对其中的Deflate数据进行解码。
> 
> 此时应修改 Bili/BiliPackReader.cs 中的内容如下 (172 行开始)
> 
> ```cs
>                 case DataTypes.Gz:
>                     List<IPack> packs = new List<IPack>();
> 
>                     // Skip 2 bytes of zlib header (assuming the header is 78 DA)
>                     byte[] deflateBuffer = payloadBuffer.Skip(2).ToArray();
>                     using (MemoryStream compressedStream = new MemoryStream(deflateBuffer))
>                     {
>                         using (DeflateStream deflateStream = new DeflateStream(compressedStream, CompressionMode.Decompress))
>                         {
>                             using (MemoryStream decompressedStream = new MemoryStream())
>                             {
>                                 deflateStream.CopyTo(decompressedStream);
>                                 decompressedStream.Position = 0;
> 
>                                 while (decompressedStream.Position != decompressedStream.Length)
>                                 {
>                                     IPack[] innerPackes = new BiliPackReader(decompressedStream).ReadPacksAsync();
>                                     packs.AddRange(innerPackes);
>                                 }
> 
>                             }
>                         }
>                     }
>                     return packs.ToArray();
> ```
> 
> 注：这是个简化的解决方案，其中假设ZLIB头为78 DA，并直接跳过了头部的检查。在正式项目中最好对ZLIB头部执行额外的检查。

已试验，可行。谢谢！
